version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: ums
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
