"""empty message

Revision ID: f15c9599fdda
Revises: 
Create Date: 2024-07-07 17:19:34.405508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f15c9599fdda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_tokens')
    op.add_column('students', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('students', sa.Column('code', sa.String(length=10), nullable=True))
    op.add_column('students', sa.Column('gpa', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('major', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'majors', ['major'], ['id'], ondelete='CASCADE')
    op.add_column('teachers', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('teachers', sa.Column('code', sa.String(length=10), nullable=True))
    op.add_column('teachers', sa.Column('major', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teachers', 'majors', ['major'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('dob', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'gender')
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'major')
    op.drop_column('teachers', 'code')
    op.drop_column('teachers', 'id')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'major')
    op.drop_column('students', 'gpa')
    op.drop_column('students', 'code')
    op.drop_column('students', 'id')
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reset_token', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='password_reset_tokens_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'reset_token', name='password_reset_tokens_pkey')
    )
    # ### end Alembic commands ###
